JSONtestWebsite/Controllers/CommentController.cs
using JSONtestWebsite.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static JSONtestWebsite.Models.CommentModel;

namespace JSONtestWebsite.Controllers
{
    public class CommentController : Controller
    {
        //GET: Comment
        public async Task<ActionResult> Index()
        {
            List<Comment> result = new List<Comment>();

            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/");

                client.DefaultRequestHeaders.Clear();

                //Define request data format to JSON
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource 
                HttpResponseMessage Res = await client.GetAsync("https://jsonplaceholder.typicode.com/comments");

                //Check response sucessful
                if (Res.IsSuccessStatusCode)
                {
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    result = JsonConvert.DeserializeObject<List<Comment>>(Response);
                }
                //Return the User list to view
                return View(result);
            }
        }
    }
}

JSONtestWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JSONtestWebsite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

JSONtestWebsite/Controllers/PostController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;
using static JSONtestWebsite.Models.PostModel;

namespace JSONtestWebsite.Controllers
{
    public class PostController : Controller
    {
        public async Task<ActionResult> Index()
        {
            List<Posting> PostInfo = new List<Posting>();

            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/");

                client.DefaultRequestHeaders.Clear();

                //Define request data format to JSON
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource 
                HttpResponseMessage Res = await client.GetAsync("https://jsonplaceholder.typicode.com/posts");

                //Check response sucessful
                if (Res.IsSuccessStatusCode)
                {
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    PostInfo = JsonConvert.DeserializeObject<List<Posting>>(Response);

                }
                //Return the Post list to view
                return View(PostInfo);
            }
        }

        
            

        //Update

        //Delete
    }
}

JSONtestWebsite/Controllers/UserController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;
using static JSONtestWebsite.Models.UserModel;
using static JSONtestWebsite.Models.CommentModel;
using static JSONtestWebsite.Models.PostModel;

namespace JSONtestWebsite.Controllers
{
    public class UsersController : Controller
    {
        //GET: Users
        public async Task<ActionResult> Index()
        {
            List<User> UserInfo = new List<User>();

            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/");

                client.DefaultRequestHeaders.Clear();

                //Define request data format to JSON
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource 
                HttpResponseMessage Res = await client.GetAsync("https://jsonplaceholder.typicode.com/users");

                //Check response sucessful
                if (Res.IsSuccessStatusCode)
                {
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    UserInfo = JsonConvert.DeserializeObject<List<User>>(Response);
                }
                //Return the User list to view
                return View(UserInfo);
            }
        }

    public async Task<ActionResult> PostHistory()
    {
            PostHistory userHistory = new PostHistory();
            User UserInfo = new User();
            List<Posting> PostInfo = new List<Posting>();
            //List<Comment> CommentInfo = new List<Comment>();

            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/");

                client.DefaultRequestHeaders.Clear();

                //Define request data format to JSON
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource 
                HttpResponseMessage Res = await client.GetAsync("https://jsonplaceholder.typicode.com/users/" + 1);
                HttpResponseMessage Res2 = await client.GetAsync("https://jsonplaceholder.typicode.com/posts?userId=1");
                //HttpResponseMessage Res3 = await client.GetAsync("https://jsonplaceholder.typicode.com/comment?postId=" + 1);


                //Check response sucessful
                if (Res.IsSuccessStatusCode)
                {
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    UserInfo = JsonConvert.DeserializeObject<User>(Response);
                }
                if (Res2.IsSuccessStatusCode)
                {
                    var Response2 = Res2.Content.ReadAsStringAsync().Result;
                    PostInfo = JsonConvert.DeserializeObject<List<Posting>>(Response2);
                }
                /*if (Res3.IsSuccessStatusCode)
                {
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    CommentInfo = JsonConvert.DeserializeObject<List<Comment>>(Response);
                }*/

                userHistory.id = UserInfo.id;
                userHistory.name = UserInfo.name;
                userHistory.username = UserInfo.username;
                userHistory.email = UserInfo.email;
                userHistory.post = PostInfo;

                //Return the User list to view
                return View(userHistory);
            }
        }
    }

        //Update

        //Delete
    
}

JSONtestWebsite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

JSONtestWebsite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

JSONtestWebsite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome!</h1>
    <p class="lead">This application utilizes C#/ASP.NET to deserialize JSON data and present it to visitors</p>
    <p><a href="https://jsonplaceholder.typicode.com/">All datasets are provided by jsonplaceholder.typicode.com </a></p>
</div>


<div class="row">
    <div class="col-lg-12">  
        <p> User directory: This page will retrieve and display a list of 10 users availble.
        <a class="btn btn-default" @Html.ActionLink("Click Here", "Index", "Users")</a>
        </p>        
    </div>
    <div class="col-lg-12">
        <p> User Posts: This page will retrieve and display all user postings (100 items).
        <a class="btn btn-default" @Html.ActionLink("Click Here", "Index", "Post")</a>
        </p>
    </div>
    <div class="col-lg-12">
        <p>
            Comments: This page retrieve and display all comment response to the main posts as is.
            <a class="btn btn-default" @Html.ActionLink("Click Here", "Index", "Comment")</a>
        </p>
    </div>
    <div class="col-lg-12">
        <p>
            Posts and comment responses: This page displays the top level Post follow by other user comment response. PK is postId.
            <a class="btn btn-default" @Html.ActionLink("Work in Progress", "", "Comment")</a>
        </p>
    </div>

</div>